# Use the official Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script and requirements file
COPY prod.py requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Run the application
CMD ["python", "prod.py"]