apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  name: {{ .Values.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: {{ .Values.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
  sessionAffinity: None
  type: {{ .Values.service.type }}